In [17]:
import pandas as pd
from pathlib import Path

BASE_DIR = Path("../data/outputs")
dataset_path =BASE_DIR / "result_test.csv"

df = pd.read_csv(dataset_path)

df.head(10)

,date,description_raw,description_normalized,amount_cents,signed_amount_cents,direction,transaction_type,balance_after_cents,doc_number,transaction_code,source_page,source_text,extraction_method,warnings,review_required
0,2026-07-01,"400,00 (+) 71493 879671493190456 Dep dinheiro ...",Dep dinheiro ATM 01/07 19:04 SOP-DIVINOPOLIS,40000,40000,credit,deposito,40000,879671493190456,71493,1,"400,00 (+) 71493 879671493190456 Dep dinheiro ...",llm,NaN,False
1,2026-07-06,"1.000,00 (+) 75634 879675634190644 Dep dinheir...",Dep dinheiro ATM 06/07 19:06 SOP-DIVINOPOLIS,100000,100000,credit,deposito,140000,879675634190644,75634,1,"1.000,00 (+) 75634 879675634190644 Dep dinheir...",llm,NaN,False
2,2026-07-06,"400,00 (-) 13105 70601 Pix - Enviado 04/07 11:...",Pix - Enviado 04/07 11:22 JOAO VITOR REZENDE M...,-40000,-40000,debit,pix,100000,70601,13105,1,"400,00 (-) 13105 70601 Pix - Enviado 04/07 11:...",llm,NaN,False
3,2026-07-08,"629,00 (-) 13105 70801 Pix - Enviado 08/07 20:...",Pix - Enviado 08/07 20:42 JOAO EDUARDO JULIO C...,-62900,-62900,debit,pix,37000,70801,13105,1,"629,00 (-) 13105 70801 Pix - Enviado 08/07 20:...",llm,NaN,False
4,2026-07-08,"221,00 (-) 13105 70802 Pix - Enviado 08/07 20:...",Pix - Enviado 08/07 20:48 JOAO VITOR REZENDE M...,-22100,-22100,debit,pix,15000,70802,13105,1,"221,00 (-) 13105 70802 Pix - Enviado 08/07 20:...",llm,NaN,False
5,2026-07-14,"93,50 (+) 14397 142250094869771 Pix - Recebido...",Pix - Recebido 14/07 22:50 14461041689 JOAO VI...,9350,9350,credit,pix,24150,142250094869771,14397,1,"93,50 (+) 14397 142250094869771 Pix - Recebido...",llm,NaN,False
6,2026-07-14,"93,50 (-) 13105 71401 Pix - Enviado 14/07 22:0...",Pix - Enviado 14/07 22:03 LA PASTA RESTAURANTE...,-9350,-9350,debit,pix,14800,71401,13105,1,"93,50 (-) 13105 71401 Pix - Enviado 14/07 22:0...",llm,NaN,False
7,2026-07-15,"133,85 (-) 13105 71501 Pix - Enviado 15/07 14:...",Pix - Enviado 15/07 14:11 JOAO EDUARDO JULIO C...,-13385,-13385,debit,pix,11415,71501,13105,1,"133,85 (-) 13105 71501 Pix - Enviado 15/07 14:...",llm,NaN,False
8,2026-07-15,"16,15 (-) 13105 71502 Pix - Enviado 15/07 14:1...",Pix - Enviado 15/07 14:11 JOAO VITOR REZENDE M...,-1615,-1615,debit,pix,9800,71502,13105,1,"16,15 (-) 13105 71502 Pix - Enviado 15/07 14:1...",llm,NaN,False
9,2026-07-15,"0,00 (+) 13105 71502 Pix - Enviado 15/07 14:11...",Pix - Enviado 15/07 14:11 JOAO VITOR REZENDE M...,0,0,credit,pix,9800,71502,13105,1,"0,00 (+) 13105 71502 Pix - Enviado 15/07 14:11...",llm,NaN,False

In [19]:
import pandas as pd
from pathlib import Path

BASE_DIR = Path("../data/outputs")
dataset_path =BASE_DIR / "result_test_500_ficticias.csv"

df = pd.read_csv(dataset_path)

df.head(500)

,date,description_raw,description_normalized,amount_cents,signed_amount_cents,direction,transaction_type,balance_after_cents,doc_number,transaction_code,source_page,source_text,extraction_method,warnings,review_required,category
0,2025-01-01,"1.548,85 (+) 64207 700000000000163 Dep dinheir...",Dep dinheiro ATM 01/01 12:50 CENTRO,154885,154885,credit,deposito,404885,700000000000163,64207,1,"1.548,85 (+) 64207 700000000000163 Dep dinheir...",synthetic,NaN,False,deposito
1,2025-01-02,"94,23 (-) 13015 700000000001154 Pix - Enviado ...",Pix - Enviado 02/01 16:58 MANUTENÇÃO E OFICINA,-9423,-9423,debit,pix,395462,700000000001154,13015,1,"94,23 (-) 13015 700000000001154 Pix - Enviado ...",synthetic,NaN,False,manutenção
2,2025-01-03,"373,74 (-) 53369 700000000002066 Pix - Enviado...",Pix - Enviado 03/01 11:27 PARCELA DE FINANCIAM...,-37374,-37374,debit,pix,358088,700000000002066,53369,1,"373,74 (-) 53369 700000000002066 Pix - Enviado...",synthetic,NaN,False,financeamento
3,2025-01-05,"558,20 (-) 69535 700000000003755 Pix - Enviado...",Pix - Enviado 05/01 07:27 PAGAMENTO DE MULTA,-55820,-55820,debit,pix,302268,700000000003755,69535,1,"558,20 (-) 69535 700000000003755 Pix - Enviado...",synthetic,NaN,False,multas
4,2025-01-06,"708,13 (-) 22742 700000000004844 Pix - Enviado...",Pix - Enviado 06/01 22:43 MANUTENÇÃO E OFICINA,-70813,-70813,debit,pix,231455,700000000004844,22742,1,"708,13 (-) 22742 700000000004844 Pix - Enviado...",synthetic,NaN,False,manutenção
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,2026-12-19,"657,49 (-) 79059 700000000493616 Pix - Enviado...",Pix - Enviado 19/12 18:24 MANUTENÇÃO E OFICINA,-65749,-65749,debit,pix,36567,700000000493616,79059,15,"657,49 (-) 79059 700000000493616 Pix - Enviado...",synthetic,NaN,False,manutenção
496,2026-12-21,"611,07 (+) 30250 700000000495025 Transferência...",Transferência recebida 21/12 18:31 PAGAMENTO D...,61107,61107,credit,transferencia,97674,700000000495025,30250,15,"611,07 (+) 30250 700000000495025 Transferência...",synthetic,NaN,False,oagamento
497,2026-12-22,"2.125,32 (+) 98427 700000000496366 Transferênc...",Transferência recebida 22/12 11:40 PAGAMENTO D...,212532,212532,credit,transferencia,310206,700000000496366,98427,15,"2.125,32 (+) 98427 700000000496366 Transferênc...",synthetic,NaN,False,oagamento
498,2026-12-24,"79,05 (-) 89607 700000000497193 Pix - Enviado ...",Pix - Enviado 24/12 21:48 PAGAMENTO DE IPVA,-7905,-7905,debit,pix,302301,700000000497193,89607,15,"79,05 (-) 89607 700000000497193 Pix - Enviado ...",synthetic,NaN,False,ipva
499,2026-12-25,"55,26 (-) 42157 700000000497742 Pix - Enviado ...",Pix - Enviado 25/12 18:48 PARCELA DE SEGURO,-5526,-5526,debit,pix,296775,700000000497742,42157,15,"55,26 (-) 42157 700000000497742 Pix - Enviado ...",synthetic,NaN,False,seguro